#!/usr/bin/env bash
# =============================================================================
# run_verilog_sim.sh
# Called by Code Runner with the currently open file as $1
# Expected project structure:
#   my_project/
#   ├── src/   ← all design .v/.sv files
#   ├── tb/    ← testbench files (*_tb.v or *_tb.sv)
#   └── sim/   ← created automatically, all output goes here
# =============================================================================

set -e

# -----------------------------------------------------------------------------
# 1. Parse inputs
# -----------------------------------------------------------------------------
FILE="$1"

if [ -z "$FILE" ]; then
    echo "Error: no file provided. Run this script via Code Runner."
    exit 1
fi

EXT="${FILE##*.}"
BASENAME="$(basename "$FILE" ".$EXT")"
TB_DIR="$(cd "$(dirname "$FILE")" && pwd)"   # absolute path of tb/
PROJECT_ROOT="$(cd "$TB_DIR/.." && pwd)"     # absolute path of project root

SRC_DIR="$PROJECT_ROOT/src"
SIM_DIR="$PROJECT_ROOT/sim"

# -----------------------------------------------------------------------------
# 2. Validate: must be a .v or .sv file
# -----------------------------------------------------------------------------
if [[ "$EXT" != "v" && "$EXT" != "sv" ]]; then
    echo "Error: '$FILE' is not a Verilog/SystemVerilog file (.v or .sv)."
    exit 1
fi

# -----------------------------------------------------------------------------
# 3. Validate: must be inside a tb/ folder
# -----------------------------------------------------------------------------
if [[ "$(basename "$TB_DIR")" != "tb" ]]; then
    echo "Error: '$FILE' is not inside a tb/ folder."
    echo "  Found in: $TB_DIR"
    echo "  Run this script on a testbench file inside your project's tb/ directory."
    exit 1
fi

# -----------------------------------------------------------------------------
# 4. Validate: file must look like a testbench (_tb suffix)
# -----------------------------------------------------------------------------
if [[ "$BASENAME" != *_tb ]]; then
    echo "Warning: '$BASENAME.$EXT' doesn't follow the *_tb naming convention."
    echo "  Continuing anyway — make sure this is actually a testbench."
    echo ""
fi

# -----------------------------------------------------------------------------
# 5. Validate: src/ must exist and contain at least one HDL file
# -----------------------------------------------------------------------------
if [ ! -d "$SRC_DIR" ]; then
    echo "Error: src/ directory not found at '$SRC_DIR'."
    echo "  Expected project structure:"
    echo "    $(basename "$PROJECT_ROOT")/"
    echo "    ├── src/   ← design files go here"
    echo "    └── tb/    ← testbench files go here"
    exit 1
fi

shopt -s nullglob
SRC_FILES=("$SRC_DIR"/*.v "$SRC_DIR"/*.sv)
shopt -u nullglob

if [ ${#SRC_FILES[@]} -eq 0 ]; then
    echo "Error: no .v or .sv files found in '$SRC_DIR'."
    exit 1
fi

# -----------------------------------------------------------------------------
# 6. Set up sim/ output directory
# -----------------------------------------------------------------------------
mkdir -p "$SIM_DIR"

SIM_OUT="$SIM_DIR/sim.out"
VCD_FILE="$SIM_DIR/dump.vcd"
VCD_INJECT="$SIM_DIR/vcd_inject.v"

# -----------------------------------------------------------------------------
# 7. Generate vcd_inject.v — adds $dumpfile/$dumpvars without touching sources
# -----------------------------------------------------------------------------
cat > "$VCD_INJECT" <<EOF
// Auto-generated by run_verilog_sim.sh — do not edit
module _vcd_inject;
initial begin
    \$dumpfile("$VCD_FILE");
    \$dumpvars(0);
end
endmodule
EOF

# -----------------------------------------------------------------------------
# 8. Compile
# -----------------------------------------------------------------------------
echo "Project root : $PROJECT_ROOT"
echo "Testbench    : $FILE"
echo "Sources      : ${#SRC_FILES[@]} file(s) from src/"
echo ""
echo "Compiling with Icarus Verilog..."

if iverilog \
    -g2012 \
    -o "$SIM_OUT" \
    "${SRC_FILES[@]}" \
    "$FILE" \
    "$VCD_INJECT"; then
    echo "Compilation successful."
    echo ""
else
    echo "Compilation failed."
    exit 1
fi

# -----------------------------------------------------------------------------
# 9. Simulate
# -----------------------------------------------------------------------------
echo "Running simulation..."
echo ""

# Run vvp from sim/ so any relative paths in the design resolve there
cd "$SIM_DIR"
vvp "$SIM_OUT"

echo ""
echo "Simulation complete. VCD written to: $VCD_FILE"

# -----------------------------------------------------------------------------
# 10. Open waveform viewer
# If Surfer VSCode extension is installed it will auto-detect the VCD change.
# Uncomment the gtkwave line below if you prefer GTKWave instead.
# -----------------------------------------------------------------------------

# GTKWave (uncomment to use):
# WAVES_SAVE="$PROJECT_ROOT/sim/waves.gtkw"
# if [ -f "$WAVES_SAVE" ]; then
#     gtkwave "$VCD_FILE" "$WAVES_SAVE" &
# else
#     gtkwave "$VCD_FILE" &
# fi

echo "Waveform ready — open $VCD_FILE in Surfer."